version: '3.9'

services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8999:80'
        environment:
            - NODE_ENV=production
        volumes:
            - ./src:/app/src
            - .:/app
volumes:
    app-data:
